name: Flutter Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0' # sesuaikan dengan versi Flutter kamu

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      # Kalau mau build web:
      # - name: Build Web
      #   run: flutter build web
